### PR TITLE
[#234] fix undefined method #and by removing nils from array

### LINKED ISSUE #234: undefined method `and' for nil:NilClass when search string is comma-separated
If `searchable_columns` is an empty array and `params[:search][:value]` is a comma-separated string, `ActiveRecord#build_conditions_for_datatable` crashes with 
```
NoMethodError: undefined method `and' for nil:NilClass
Did you mean?  rand
./lib/ajax-datatables-rails/orm/active_record.rb:43:in `each'
./lib/ajax-datatables-rails/orm/active_record.rb:43:in `reduce'
./lib/ajax-datatables-rails/orm/active_record.rb:43:in `build_conditions_for_datatable'
./lib/ajax-datatables-rails/orm/active_record.rb:29:in `build_conditions'
./lib/ajax-datatables-rails/orm/active_record.rb:10:in `filter_records'
./lib/ajax-datatables-rails/base.rb:87:in `retrieve_records'
./lib/ajax-datatables-rails/base.rb:49:in `records'
./spec/support/test_helpers.rb:97:in `data'
```

### PR DESCRIPTION
**Pull request by kv109**
Fixes #234

### CODE REVIEW

File: spec/ajax-datatables-rails/base_spec.rb [hunk 1]
```diff
@@ -86,6 +86,26 @@
...
+          let(:datatable) do
+            ComplexDatatableArray.new(view).tap do |datatable|
+              datatable.instance_variable_set :@searchable_columns, []
+            end
+          end
+
+          context 'when search value is comma-separated string' do
+            let(:view) { double('view', params: sample_params.merge(search: { value: 'one, two' })) }
+
+            it 'should return an array of arrays' do
```
Comment (kv109) [inline spec/ajax-datatables-rails/base_spec.rb:100]: This test fails without https://github.com/jbox-web/ajax-datatables-rails/pull/235/commits/45fde7e3780c2a40275d08ad4b01156cf33d2f17.

**Comment by n-rodriguez** [comment]
Thank you!
